ead:
  service:
    registry:
      username: serviceregistry
      password: ead123sr

eureka:
  client:
    service-url:
      default-zone: 'http://${ead.service.registry.username}:${ead.service.registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost