server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: authuser-service
            uri: lb://EAD-AUTHUSER-SERVICE
            predicates:
              - Path=/ead-authuser/**
          - id: course-service
            uri: lb://EAD-COURSE-SERVICE
            predicates:
              - Path=/ead-course/**
          - id: notification-service
            uri: lb://EAD-NOTIFICATION-SERVICE
            predicates:
              - Path=/ead-notification/**
