server:
  port: 8086
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-payment?currentSchema=public
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: localhost
    port: 5672
    username: gabriel
    password: gabriel

broker:
  exchange:
    user:
      event: ead.userevent
    payment:
      command: ead.paymentcommand
  queue:
    user:
      event: ead.userevent.ms.payment
    payment:
      command: ead.paymentcommand.ms.payment

logging:
  level:
#    com.ead: INFO
#    root: INFO
#    org.springframework.web: INFO
#    org.hibernate: INFO
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health