version: "3.8"
services:
  curso-dev-rabbitmq:
    image: rabbitmq:3.13.0-management
    container_name: produto-dev-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=gabriel
      - RABBITMQ_DEFAULT_PASS=gabriel
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    volumes:
      - ./vol-data:/var/lib/rabbitmq/
    networks:
      - backend
networks:
  backend:
    driver: bridge