version: "3.8"
services:
  contrato-dev-mysql:
    image: mysql:8.2.0
    container_name: contrato-dev-mysql
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contrato_dev
    ports:
      - 3307:3306
    volumes:
      - ./vol-db:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge